services:
  - type: web
    name: chatbot-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_ORG_ID
        sync: false
      - key: OPENAI_ASSISTANT_ID
        sync: false 